version: '3'
services:
  postgres:
    build:
      context: ./server
      dockerfile: Dockerfile-database
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=retr.dev
      - LETSENCRYPT_HOST=retr.dev
    depends_on:
      - postgres