version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
        - ./server/schema.sql:/docker-entrypoint.initdb.d/1-schema.sql
  server:
    build: ./server/